### PR TITLE
Fix OnLeftFoot and OnRightFoot joints position for iCubGazeboV2_5

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This fixes the joints position for the left and right one foot balancing (for iCubGazeboV2_5)

|       | Previous | Fixed |
|:-----:|:--------:|:-----:|
|  **Left** |   leftfail       |  leftfix     |
| **Right** |     rightfail    |    rightfix   |

### CODE REVIEW

**Comment by traversaro** [comment]
@GiulioRomualdi @gabrielenava not urgent, but eventually we need to find a better place were to host these configuration files. I do not have a clear idea on this, to be honest. For which repo are this used? if they are just used for whole-body-controllers, it could make sense to keep them there.

**Comment by traversaro** [comment]
@GiulioRomualdi indeed, with "better place" I meant another repo. `robots-configuration` could make sense, but it has several complexities (it is used by a lot of robots, its files are actually generated with an automatic procedure not perfectly documented) so it could make sense to have another place for it.

**Comment by gabrielenava** [comment]
>@GiulioRomualdi @gabrielenava not urgent, but eventually we need to find a better place were to host these configuration files. I do not have a clear idea on this, to be honest. For which repo are this used? if they are just used for whole-body-controllers, it could make sense to keep them there.

I have no clear idea about where to put these files, but I agree that the current location is not easy to find. Maybe at this point it may makes sense to put them in `whole-body-controllers`.

**Comment by traversaro** [comment]
> Maybe at this point it may makes sense to put them in whole-body-controllers.

I think we need a place where they get installed using the robotology-superbuild with `ROBOTOLOGY_ENABLE_DYNAMICS` is set to ON and `ROBOTOLOGY_USES_MATLAB` set to `OFF`. `whole-body-controllers`at the moment is not installed at all if `ROBOTOLOGY_USES_MATLAB` is set to `OFF`.

**Comment by traversaro** [comment]
@gabrielenava @GiulioRomualdi can we merge this?

**Comment by gabrielenava** [comment]
For me we can merge.

**Pull request merged**
