### PR TITLE
Bump version to 0.3.0

### PR DESCRIPTION
**Pull request by traversaro**
This is just to have a clear version related to the current state of codyco-modules, so that we can tag it for future reference and finally deprecate it.

### CODE REVIEW

**Comment by traversaro** [comment]
Friendly ping @HosameldinMohamed @nunoguedelha @prashanthr05

**Comment by prashanthr05** [comment]
What were the changes associated with this minor version bump?

**Comment by prashanthr05** [comment]
Also, do we worry that the Travis complains about a mismatch in YARP versions?

**Comment by traversaro** [comment]
> Also, do we worry that the Travis complains about a mismatch in YARP versions?

Travis is hopelessly broken in this repo, that is the reason I wanted to migrate everything valuable in whole-body-estimators in https://github.com/robotology/whole-body-estimators/pull/16 . I do not think it makes sense to spend time in fixing the CI here.

**Comment by traversaro** [comment]
> What were the changes associated with this minor version bump?

Who knows. : ) 
Jokes apart, we never maintained a CHANGELOG file for this repo, and I do not think it is worth the effort trying to reconstruct one now. I updated the original PR description to better describe why I wanted to bump the version.

**Comment by traversaro** [comment]
In particular this was used for https://github.com/robotology/robotology-superbuild/issues/331 .

**Review by prashanthr05 — APPROVED** [review]

**Pull request merged**
