### PR TITLE
Disable JTC for YARP >= 2.3.68.8

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/robotology/codyco-modules/issues/230 . 

@gabrielenava @diegoferigo Feel free to merge as soon as the Travis return successful.

### CODE REVIEW

**Comment by gabrielenava** [comment]
the previous error is now solved, but the compilation still stops here:

``` /home/gnava/Software/codyco-superbuild/main/codyco-modules/src/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp: In member function ‘void yarp::dev::WholeBodyDynamicsDevice::publishGravityCompensation()’:
/home/gnava/Software/codyco-superbuild/main/codyco-modules/src/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp:1466:22: error: ‘VOCAB_CM_OPENLOOP’ was not declared in this scope
                 case VOCAB_CM_OPENLOOP:
                      ^
src/devices/wholeBodyDynamics/CMakeFiles/wholeBodyDynamicsDevice.dir/build.make:86: recipe for target 'src/devices/wholeBodyDynamics/CMakeFiles/wholeBodyDynamicsDevice.dir/WholeBodyDynamicsDevice.cpp.o' failed
make[5]: *** [src/devices/wholeBodyDynamics/CMakeFiles/wholeBodyDynamicsDevice.dir/WholeBodyDynamicsDevice.cpp.o] Error 1
CMakeFiles/Makefile2:577: recipe for target 'src/devices/wholeBodyDynamics/CMakeFiles/wholeBodyDynamicsDevice.dir/all' failed
make[4]: *** [src/devices/wholeBodyDynamics/CMakeFil
```

**Comment by gabrielenava** [comment]
temporarily solved by commenting out the line `VOCAB_CM_OPENLOOP` in [wholeBodyDynamicsDevice.cpp](https://github.com/robotology/codyco-modules/blob/master/src/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp):

```
            switch(ctrl_mode)
            {
                //for all this control modes do nothing
                //case VOCAB_CM_OPENLOOP:
                case VOCAB_CM_IDLE:
                case VOCAB_CM_UNKNOWN:
                case VOCAB_CM_HW_FAULT:
                    break;
```

this last modification make the `codyco-modules` able to compile. However, now this error moved to `gazebo-yarp-plugins`:

```
In file included from /home/gnava/Software/codyco-superbuild/libraries/GazeboYARPPlugins/plugins/controlboard/src/ControlBoard.cc:8:0:
/home/gnava/Software/codyco-superbuild/libraries/GazeboYARPPlugins/plugins/controlboard/include/yarp/dev/ControlBoardDriver.h:13:39: fatal error: yarp/dev/IOpenLoopControl.h: No such file or directory
compilation terminated.
plugins/controlboard/CMakeFiles/gazebo_yarp_controlboard.dir/build.make:62: recipe for target 'plugins/controlboard/CMakeFiles/gazebo_yarp_controlboard.dir/src/ControlBoard.cc.o' failed
make[5]: *** [plugins/controlboard/CMakeFiles/gazebo_yarp_controlboard.dir/src/ControlBoard.cc.o] Error 1
CMakeFiles/Makefile2:506: recipe for target 'plugins/controlboard/CMakeFiles/gazebo_yarp_controlboard.dir/all' failed
make[4]: *** [plugins/controlboard/CMakeFiles/gazebo_yarp_controlboard.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/GazeboYARPPlugins.dir/build.make:106: recipe for target 'libraries/GazeboYARPPlugins/CMakeFiles/YCMStamp/GazeboYARPPlugins-build' failed
make[2]: *** [libraries/GazeboYARPPlugins/CMakeFiles/YCMStamp/GazeboYARPPlugins-build] Error 2
CMakeFiles/Makefile2:716: recipe for target 'CMakeFiles/GazeboYARPPlugins.dir/all' failed
make[1]: *** [CMakeFiles/GazeboYARPPlugins.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

```

I think I choose the wrong day for updating codyco-superbuild

**Comment by traversaro** [comment]
`gazebo-yarp-plugins` should be on `devel` as well.

**Comment by gabrielenava** [comment]
still not the end:

```
[ 98%] Performing build step for 'yarp-matlab-bindings'
Scanning dependencies of target yarpMEX
[ 50%] Building CXX object matlab/CMakeFiles/yarpMEX.dir/yarpMATLAB_wrap.cxx.o
/home/gnava/Software/codyco-superbuild/libraries/yarp-matlab-bindings/matlab/yarpMATLAB_wrap.cxx: In function ‘bool yarp_os_ResourceFinder_configure__SWIG_4(yarp::os::ResourceFinder*, const string&, std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >&, bool)’:
/home/gnava/Software/codyco-superbuild/libraries/yarp-matlab-bindings/matlab/yarpMATLAB_wrap.cxx:2540:22: warning: ‘bool yarp::os::ResourceFinder::configure(const char*, int, char**, bool)’ is deprecated [-Wdeprecated-declarations]
       (char**)&tmp[0]);
                      ^
In file included from /home/gnava/Software/INSTALL/include/yarp/os/RFModule.h:14:0,
                 from /home/gnava/Software/INSTALL/include/yarp/os/all.h:58,
                 from /home/gnava/Software/codyco-superbuild/libraries/yarp-matlab-bindings/matlab/yarpMATLAB_wrap.cxx:2146:
/home/gnava/Software/INSTALL/include/yarp/os/ResourceFinder.h:107:26: note: declared here
     YARP_DEPRECATED bool configure(const char *policyName, int argc, char *argv
                          ^
/home/gnava/Software/codyco-superbuild/libraries/yarp-matlab-bindings/matlab/yarpMATLAB_wrap.cxx: At global scope:
/home/gnava/Software/codyco-superbuild/libraries/yarp-matlab-bindings/matlab/yarpMATLAB_wrap.cxx:2668:23: error: ‘IOpenLoopControl’ in namespace ‘yarp::dev’ does not name a type

```

**Pull request merged**
