### PR TITLE
Torquebalancing/references in streaming

### PR DESCRIPTION
**Pull request by francesco-romano**
Updated torque balancing

@traversaro I need a fast review on the *** part :)

I'll merge it

### CODE REVIEW

**Comment by traversaro** [comment]
(We should disable linthub until they make it configurable..).

**Comment by traversaro** [comment]
Done.

**Comment by francesco-romano** [comment]
@traversaro 
- done. I will commit it. 
- This is not enough imho. I can remove the `readStatus()` from the method I added and add it to the run, but still the references need to be copied.
- Ok. I was sure there was an `if joint is not in torque mode`.. I'll edit the code.

**Comment by traversaro** [comment]
> This is not enough imho. I can remove the readStatus() from the method I added and add it to the run, but still the references need to be copied.

But why we can't simply copy the references when we call the `startHijackingTorqueControl` method?

**Comment by francesco-romano** [comment]
We can do. The reasons I didn't do it yesterday were:
- at the beginning I used (wrongly) a `memcpy` because I wanted to set all the torques at once, and the `startHijackingTorqueControl` doesn't allow it.
- `startHijackingTorqueControl` is called even if the current joint is in torque mode, thus resetting the reference. I can change the code to change this behaviour if you prefer.

**Comment by traversaro** [comment]
By getting rid of `setDefaultReferencesOnModeSwitch`/`newlySwitchedControlModes` stuff we transform a 120 lines modification in a 6 lines much more readable modification. I can do the change if you want.

**Comment by francesco-romano** [comment]
Done. Take a look at it. 
If it is ok I'll test it asap on the robot before merging

**Comment by traversaro** [comment]
:+1:

**Comment by francesco-romano** [comment]
@DanielePucci 
@traversaro and me have "reviewed" this PR.
Given the changes on *** , we need to test it again on the robot before merging.
To do this:
```bash
git checkout master
git branch -D torquebalancing/references_in_streaming
git fetch
git checkout torquebalancing/references_in_streaming
```

**Comment by traversaro** [comment]
cc @francesco-romano

**Comment by francesco-romano** [comment]
Waiting to test on the robot.

**Comment by traversaro** [comment]
Yes I know, I wanted to notify you of the changes on the configuration files stuff.

**Comment by traversaro** [comment]
cc @drdanz can we disable linthub for this repo? The idea is cool, but until it is configurable it creates to much noise.

**Comment by francesco-romano** [comment]
Oh I didn't notice it!
Fortunately you told me..
Next time I have to fork the repo..I usually force push on this branch..

Inviato da iPhone

**Comment by traversaro** [comment]
I will probably merge this branch in `wbdCleanup` for used here in heideleberg, so I guess it is cleaner if we avoid to force push on this branch from now on.

**Comment by drdanz** [comment]
@traversaro I unticked the "active" checkbox in the webhook configuration, so that it will be easy to re-enable it later, but I'm not 100% sure that it actually disables it... let me know if it is still enabled

**Comment by traversaro** [comment]
@drdanz disabled, thanks!

**Pull request merged**
