### PR TITLE
updated home poses for iCubNancy01 

### PR DESCRIPTION
**Pull request by gabrielenava**
Updated the home positions for Yoga and standup demos (and also the others homePos)

### CODE REVIEW

**Comment by francesco-romano** [comment]
@gabrielenava given the new yarpmotorgui feature, why adding all these files?
I would add only the `homePoseBalancing.ini` file

**Comment by traversaro** [comment]
Ping @gabrielenava .

**Comment by gabrielenava** [comment]
I'm trying to do this now but apparently I do not have the permissions to push in this repo anymore

**Comment by traversaro** [comment]
Yes, I removed them from the `codyco-developers` team, and I have added them to each person individually, and I forgot about you. You have been added back. 

In the medium term, it would be nice if PR could be created using branches on user's private fork, and only the repository maintainers had the permission to merge PRs. We are not there yet, but please check with @diegoferigo about this.

**Comment by gabrielenava** [comment]
done at https://github.com/robotology/codyco-modules/pull/235/commits/08636bad8ce7b0a440abb78b09c36ecbb98975d7

**Comment by gabrielenava** [comment]
is it possible to merge this issue?

**Comment by traversaro** [comment]
Done.

**Pull request merged**
