### PR TITLE
TorqueBalancing: app for upper-body kin teach-in |  Darmstadt

### PR DESCRIPTION
**Pull request by paraschos**
Hey @francesco-romano, @traversaro 

I created an app that facilitates data collection using kinesthetic teach-in 
while the robot is balancing using the torque ctl. Quite simple stuff for the moment,
just the  torqueBalancingAppTwoFeet that starts the torqueBalancing with different
gains and the new file with the gains.  The app xml also hardcodes the host 
(tomlinson) instead of being generic.

I am not sure if  it makes sense to put it in the main repo... Any suggestions?

I also re-based on top of the current master to avoid splits in history.

Cheers,
a

### CODE REVIEW

**Comment by francesco-romano** [comment]
Hi @paraschos 

For sure we can put this app in the main repository.
Before merging though, I kindly ask you to either make the app generic and not tied to the darmstadt cluster configuration (so, please generate a template app) or to move these files into the robot specific folder (i.e. `app/robots/iCubDarmstadt01`).

Ciao

**Comment by francesco-romano** [comment]
I wanted to test the new GitHub review 😆

**Comment by paraschos** [comment]
:)

**Comment by paraschos** [comment]
I will do the changes and modify the request

**Comment by traversaro** [comment]
I think it is safe to close this PR, as anyone involved in this has probably moved on. 

@paraschos I hope everything is fine in Volkswagen!

**Pull request closed without merging**
