### PR TITLE
updated home position for icub standup demo

### PR DESCRIPTION
**Pull request by gabrielenava**
as in the title

### CODE REVIEW

**Comment by traversaro** [comment]
@gabrielenava Can you solve the conflicts?

**Comment by gabrielenava** [comment]
done in https://github.com/robotology/codyco-modules/pull/220/commits/e8c1d163e73a9f50b7804b197cc03ab7313b73dd

**Comment by gabrielenava** [comment]
This branch contains now the general update of all custom configurations for yarpmotorgui. In particular:

- updated home position for iCub standup demo, both in simulation and on the real robot;
- updated home position for Walkman in simulation;
- improved custom postition support (see also https://github.com/robotology/yarp/pull/1160)
- added `iCubGenova04` custom positions folder 

tested on both `devel` and `master` branch for the following robots:
- `icubGazebSim`
- `bigman`
- `bigman_only_legs`

test on the real robot is still missing, after that I think we can merge this PR.

cc @traversaro @francesco-romano

**Comment by gabrielenava** [comment]
given that the error in the yarpmotorgui does not depend on this update (see https://github.com/robotology/yarp/issues/1196) and since this branch now contains also important modifications for the green robot, I think it is better to merge this asap

**Comment by traversaro** [comment]
@gabrielenava after the demos, can you please remove the commits related to wholeBodyDynamics from the PR so we can merge it? Thanks

**Comment by gabrielenava** [comment]
reverted wholeBodyDynamics modifications at https://github.com/robotology/codyco-modules/pull/220/commits/a238662d6b0485a96d3ce2024767ea157f81a9bb

**Comment by traversaro** [comment]
Merged, thanks @gabrielenava .

**Pull request merged**
